# nelmio_cors:
#     defaults:
#         allow_origin: ['http://localhost:4200']
#         allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#         allow_headers: ['Content-Type', 'Authorization']
#         max_age: 3600
#     paths:
#         '^/api/':
#             allow_origin: ['http://localhost:4200']
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
#             allow_headers: ['Content-Type', 'Authorization']
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        expose_headers: []
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600